openapi: 3.0.0
info:
  title: Simple Test API
  version: 1.0.0
  description: A simple API for testing
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string